services:
  app:
    #image: ares_app:1.0.0
    build: .
    container_name: ares_app
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - APP_PORT=${APP_PORT}
      - DB_LESS=${DB_LESS}
    ports:
      - "3000:3000"

  db:
    image: mysql:8.4.4
    container_name: ares_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
